enum Action {
  SIGNUP_REQUEST = "@@auth/SIGNUP_REQUEST",
  SIGNUP_SUCCESS = "@@auth/SIGNUP_SUCCESS",
  SIGNUP_FAILURE = "@@auth/SIGNUP_FAILURE",

  LOGIN_REQUEST = "@@auth/LOGIN_REQUEST",
  LOGIN_SUCCESS = "@@auth/LOGIN_SUCCESS",
  LOGIN_FAILURE = "@@auth/LOGIN_FAILURE",

  FINISH_SESSION_CHECK = "@@auth/FINISH_SESSION_CHECK",
  LOGOUT = "@@auth/LOGOUT",

  SET_EDITING_GAME_ID = "@@editor/SET_EDITING_GAME_ID",

  EDITOR_CONNECT_REQUEST = "@@editor/EDITOR_CONNECT_REQUEST",
  EDITOR_CONNECT_SUCCESS = "@@editor/EDITOR_CONNECT_SUCCESS",
  EDITOR_CONNECT_FAILURE = "@@editor/EDITOR_CONNECT_FAILURE",

  SOCKET_CONNECTED = "@@socket/SOCKET_CONNECTED",
  SOCKET_CONNECTION_DROPPED = "@@socket/SOCKET_CONNECTION_DROPPED",
  EDITOR_CONNECTION_DROPPED = "@@socket/CHANNEL_CONNECTION_DROPPED",

  EDITOR_LEAVE = "@@editor/LEAVE_EDITOR",

  RECOMPILE_REQUEST = "@@editor/RECOMPILE_REQUEST",
  RECOMPILE_SUCCESS = "@@editor/RECOMPILE_SUCCESS",
  RECOMPILE_FAILURE = "@@editor/RECOMPILE_FAILURE",

  UPLOAD_IMAGE_REQUEST = "@@assets/UPLOAD_IMAGE_REQUEST",
  UPLOAD_IMAGE_SUCCESS = "@@assets/UPLOAD_IMAGE_SUCCESS",
  UPLOAD_IMAGE_FAILURE = "@@assets/UPLOAD_IMAGE_FAILURE",

  RENAME_IMAGE_REQUEST = "@@assets/RENAME_IMAGE_REQUEST",
  RENAME_IMAGE_SUCCESS = "@@assets/RENAME_IMAGE_SUCCESS",
  RENAME_IMAGE_FAILURE = "@@assets/RENAME_IMAGE_FAILURE",

  DELETE_IMAGE_REQUEST = "@@assets/DELETE_IMAGE_REQUEST",
  DELETE_IMAGE_SUCCESS = "@@assets/DELETE_IMAGE_SUCCESS",
  DELETE_IMAGE_FAILURE = "@@assets/DELETE_IMAGE_FAILURE",

  UPLOAD_AUDIO_REQUEST = "@@assets/UPLOAD_AUDIO_REQUEST",
  UPLOAD_AUDIO_SUCCESS = "@@assets/UPLOAD_AUDIO_SUCCESS",
  UPLOAD_AUDIO_FAILURE = "@@assets/UPLOAD_AUDIO_FAILURE",

  RENAME_AUDIO_REQUEST = "@@assets/RENAME_AUDIO_REQUEST",
  RENAME_AUDIO_SUCCESS = "@@assets/RENAME_AUDIO_SUCCESS",
  RENAME_AUDIO_FAILURE = "@@assets/RENAME_AUDIO_FAILURE",

  DELETE_AUDIO_REQUEST = "@@assets/DELETE_AUDIO_REQUEST",
  DELETE_AUDIO_SUCCESS = "@@assets/DELETE_AUDIO_SUCCESS",
  DELETE_AUDIO_FAILURE = "@@assets/DELETE_AUDIO_FAILURE",

  EDIT_TILE_SIZE = "@@board/EDIT_TILE_SIZE",
  TOGGLE_SHOW_ARROWS = "@@board/TOGGLE_SHOW_ARROWS",
  TOGGLE_SHOW_IMAGES = "@@board/TOGGLE_SHOW_IMAGES",
  TOGGLE_SHOW_PATH_LINES = "@@board/TOGGLE_SHOW_PATH_LINES",
  TOGGLE_SHOW_UNUSED_TILES = "@@board/TOGGLE_SHOW_UNUSED_TILES",

  NEW_GAME_REQUEST = "@@game/NEW_GAME_REQUEST",
  NEW_GAME_SUCCESS = "@@game/NEW_GAME_SUCCESS",
  NEW_GAME_FAILURE = "@@game/NEW_GAME_FAILURE",

  DELETE_GAME_REQUEST = "@@game/DELETE_GAME_REQUEST",
  DELETE_GAME_SUCCESS = "@@game/DELETE_GAME_SUCCESS",
  DELETE_GAME_FAILURE = "@@game/DELETE_GAME_FAILURE",

  TOGGLE_GAME_VISIBILITY_REQUEST = "@@game/TOGGLE_GAME_VISIBILITY_REQUEST",
  TOGGLE_GAME_VISIBILITY_RESULT = "@@game/TOGGLE_GAME_VISIBILITY_RESULT",

  EDIT_GAME_SOURCE = "@@game/EDIT_GAME_SOURCE"
}

export default Action;
